version: 0.0
os: linux
files:
  - source: '/demo-1.0-SNAPSHOT.war'
    destination: /home/ec2-user/apache-tomcat-11.0.7/webapps
hooks:
  BeforeInstall:
   - location: BeforeInstall.sh
     runas: ec2-user
  ApplicationStop:
    - location: ApplicationStop.sh
      runas: ec2-user
  ApplicationStart:
    - location: ApplicationStart.sh
      runas: ec2-user
  ValidateService:
    - location: ValidateService.sh
      runas: ec2-user
