version: 0.2

phases:
  pre_build:
    commands:
      - echo "Nothing in pre_build"
  build:
    commands:
      - echo "running the build"
      - mvn clean package test
  post_build:
    commands:
      - echo "nothing in post build"


artifacts:
  files: */target/demo.war
