version: 0.2

phases:
  pre_build:
     commands:
      - echo "running pre build"
  build:
     commands:
      - echo "Running build"
      - mvn clean package test
  post-build:
     commands:
      - echo "Nothin to do in post build"
artifacts:
  - files: target/demo*.war
