apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: webapp-container
        image: 250190/devops
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: web-app
spec:
  selector:
    app: web-app

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
